### PR TITLE
[DevOps] Adding linting to project

### PR DESCRIPTION
**Pull request by ActuallyConnor**
# [DevOps] Adding linting to project

## Description

https://purajuniper.myjetbrains.com/youtrack/issue/SAGE-196

## Code changes

- Added eslint scripts in `package.json`
- Added husky `pre-commit` script

### Test 1

- [ ] Run `npm install`
- [ ] Verify no errors occurred

### Test 2

- [ ] Create a new branch
- [ ] Make an eslint violating change to a file
_I am not familiar with the ruleset established here to know what would constitute a violation, perhaps checking with @oyisre would be beneficial_
- [ ] Attempt to make a commit
- [ ] Verify that the pre-commit fails and it does not allow you to proceed without fixing the violation

### CODE REVIEW

**Comment by joshrliben** [comment]
@ActuallyConnor Should we make our own config file as per https://www.npmjs.com/package/eslint#installation-and-usage ?
Or do you have one you could push to this PR? (`eslintrc.json`)

**Comment by ActuallyConnor** [comment]
> @ActuallyConnor Should we make our own config file as per https://www.npmjs.com/package/eslint#installation-and-usage ? Or do you have one you could push to this PR? (`eslintrc.json`)

@joshcds, @oyisre already has an eslint file in the project so that's already accomplished 😄

**Comment by joshrliben** [comment]
Ah yes, I see it now!

@oyisre I don't see any rules in that file. That json object is empty.
How would I go about making a violation? or do we need to make a rule first?

I.e, I'm not sure what change to the code would constitute an eslint violation, or even where to find a list of them

**Comment by oyisre** [comment]
We only have rules active for .ts and .tsx files which are listed under the overrides property (the .js files were from the original FRED and we've yet to fix all the linting errors in any of those). 

One quick violation to test would be to replace some 'let' with 'var' to trigger no-var

**Review by joshrliben — APPROVED** [review]

**Pull request merged**
